# === STAGE 1: Build the Angular App ===
FROM node:18 AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies (use --no-audit for faster build in CI/CD)
RUN npm install --quiet

# Copy source code
COPY . .

# Build for production
RUN npx ng build --configuration=production


# ========= STAGE 2: Serve with Nginx =======================
FROM nginx:alpine AS production

# Copy built Angular app from builder stage
COPY --from=builder /app/dist/Angular14_Yesschool /usr/share/nginx/html
# COPY --from=builder /app/dist/* /usr/share/nginx/html

# Copy custom Nginx config (for SPA routing, headers, etc.)
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]